gateway:
  server:
    main:
      uri: "http://localhost:8078"
jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379


  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

logging:
  level:
    reactor:
      netty: DEBUG